server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${SPRING_DATASOURCE_USERNAME:platform}
    password: ${SPRING_DATASOURCE_PASSWORD:platform}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
